"""Added Department model

Revision ID: 0aa5eef0664d
Revises: 45c21179b25b
Create Date: 2025-03-09 15:46:52.641859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0aa5eef0664d'
down_revision: Union[str, None] = '45c21179b25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    # op.alter_column('blocks', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    op.add_column('books', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('is_processed', sa.Boolean(), nullable=True))
    # op.execute("UPDATE books set is_processed = TRUE")
    # op.add_column('books', sa.Column('is_processed', sa.Boolean(), nullable=False))
    # op.alter_column('books', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    op.drop_index('ix_books_department', table_name='books')
    op.create_index('ix_books_department_id', 'books', ['department_id'], unique=False)
    op.create_foreign_key(None, 'books', 'departments', ['department_id'], ['id'])
    op.drop_column('books', 'department')
    # op.alter_column('districts', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('document_types', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('gram_panchayats', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    op.add_column('grs', sa.Column('department_id', sa.Integer(), nullable=True))
    # op.alter_column('grs', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    op.drop_index('ix_gr_department_effective_date', table_name='grs')
    op.drop_index('ix_grs_department_name', table_name='grs')
    op.create_index('ix_gr_department_id_effective_date', 'grs', ['department_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_grs_department_id'), 'grs', ['department_id'], unique=False)
    op.create_foreign_key(None, 'grs', 'departments', ['department_id'], ['id'])
    op.drop_column('grs', 'department_name')
    # op.alter_column('roles', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_documents', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_documents', 'verification_status',
    #            existing_type=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
    #            type_=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
    #            existing_nullable=False)
    # op.alter_column('user_otps', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('users', 'status',
    #            existing_type=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
    #            type_=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
    #            existing_nullable=False)
    # op.alter_column('yojanas', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('yojanas', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.alter_column('users', 'status',
               existing_type=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
               type_=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
               existing_nullable=False)
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_otps', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.alter_column('user_documents', 'verification_status',
               existing_type=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
               type_=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
               existing_nullable=False)
    # op.alter_column('user_documents', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('roles', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.add_column('grs', sa.Column('department_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'grs', type_='foreignkey')
    op.drop_index(op.f('ix_grs_department_id'), table_name='grs')
    op.drop_index('ix_gr_department_id_effective_date', table_name='grs')
    op.create_index('ix_grs_department_name', 'grs', ['department_name'], unique=False)
    op.create_index('ix_gr_department_effective_date', 'grs', ['department_name', 'effective_date'], unique=False)
    # op.alter_column('grs', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.drop_column('grs', 'department_id')
    # op.alter_column('gram_panchayats', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('document_types', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('districts', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.add_column('books', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index('ix_books_department_id', table_name='books')
    op.create_index('ix_books_department', 'books', ['department'], unique=False)
    # op.alter_column('books', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.drop_column('books', 'is_processed')
    op.drop_column('books', 'department_id')
    # op.alter_column('blocks', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
