"""Adding docs_uploaded col in users model

Revision ID: 168b1e6b3481
Revises: 66d442859693
Create Date: 2025-03-24 16:01:21.403738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '168b1e6b3481'
down_revision: Union[str, None] = '66d442859693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('documents_uploaded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'documents_uploaded')
    # ### end Alembic commands ###
