"""Adding Autoincrements to id cols

Revision ID: 45c21179b25b
Revises: 53eeef77d959
Create Date: 2025-02-16 14:57:29.460218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45c21179b25b'
down_revision: Union[str, None] = '53eeef77d959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# List of tables in the "gs_schema" that require identity on "id" column.
tables = [
    'roles',
    'districts',
    'blocks',
    'gram_panchayats',
    'books',
    'document_types',
    'user_documents',
    'yojanas',
    'grs',
    'user_otps'
]


def upgrade():
    for table in tables:
        # Drop any existing default from the "id" column
        op.execute(f"""
            ALTER TABLE gs_schema.{table}
            ALTER COLUMN id DROP DEFAULT;
        """)
        # Add the identity clause
        op.execute(f"""
            ALTER TABLE gs_schema.{table}
            ALTER COLUMN id
            ADD GENERATED BY DEFAULT AS IDENTITY;
        """)


def downgrade():
    for table in tables:
        # Drop the identity property if it exists
        op.execute(f"""
            ALTER TABLE gs_schema.{table}
            ALTER COLUMN id DROP IDENTITY IF EXISTS;
        """)
        # Optionally, restore the old default.
        # Note: Adjust the sequence name as per your naming convention.
        op.execute(f"""
            ALTER TABLE gs_schema.{table}
            ALTER COLUMN id
            SET DEFAULT nextval('gs_schema.{table}_id_seq'::regclass);
        """)
