"""Added Autoincrement to user_id

Revision ID: 53eeef77d959
Revises: c4c34bef9a13
Create Date: 2025-02-15 14:37:05.449467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53eeef77d959'
down_revision: Union[str, None] = 'c4c34bef9a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # Drop the existing default from the "id" column.
    op.execute(
        """
        ALTER TABLE gs_schema.users
        ALTER COLUMN id DROP DEFAULT;
        """
    )
    # Now add the identity clause.
    op.execute(
        """
        ALTER TABLE gs_schema.users
        ALTER COLUMN id
        ADD GENERATED BY DEFAULT AS IDENTITY;
        """
    )

def downgrade():
    # To revert, first drop the identity property.
    op.execute(
        """
        ALTER TABLE gs_schema.users
        ALTER COLUMN id
        DROP IDENTITY IF EXISTS;
        """
    )
    # Optionally, re-create the old default if needed.
    op.execute(
        """
        ALTER TABLE gs_schema.users
        ALTER COLUMN id
        SET DEFAULT nextval('gs_schema.users_id_seq'::regclass);
        """
    )

# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('user_documents', 'verification_status',
#                existing_type=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
#                type_=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
#                existing_nullable=False)
#     op.alter_column('users', 'status',
#                existing_type=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
#                type_=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
#                existing_nullable=False)
#     # ### end Alembic commands ###
#
#
# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'status',
#                existing_type=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
#                type_=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
#                existing_nullable=False)
#     op.alter_column('user_documents', 'verification_status',
#                existing_type=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
#                type_=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
#                existing_nullable=False)
#     # ### end Alembic commands ###
