"""Changing enum

Revision ID: 66d442859693
Revises: 0aa5eef0664d
Create Date: 2025-03-22 12:09:16.446611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66d442859693'
down_revision: Union[str, None] = '0aa5eef0664d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('blocks', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('books', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('books', 'is_processed',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # op.alter_column('districts', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('document_types', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('gram_panchayats', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('grs', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('grs', 'department_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('roles', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_documents', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_documents', 'verification_status',
    #            existing_type=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
    #            type_=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
    #            existing_nullable=False)
    # op.alter_column('user_otps', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('users', 'status',
    #            existing_type=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
    #            type_=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
    #            existing_nullable=False)
    # op.alter_column('yojanas', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False,
    #            autoincrement=

    # op.execute("Alter enum userdesignation ADD VALUE 'ग्राम पंचायत अधिकारी', 'विस्तार अधिकारी'")


    op.execute("ALTER TYPE userdesignation ADD VALUE IF NOT EXISTS 'ग्राम पंचायत अधिकारी'")

    op.execute("ALTER TYPE userdesignation ADD VALUE IF NOT EXISTS 'विस्तार अधिकारी'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('yojanas', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('users', 'status',
    #            existing_type=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
    #            type_=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
    #            existing_nullable=False)
    # op.alter_column('users', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_otps', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('user_documents', 'verification_status',
    #            existing_type=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'),
    #            type_=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='status'),
    #            existing_nullable=False)
    # op.alter_column('user_documents', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('roles', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('grs', 'department_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('grs', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('gram_panchayats', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('document_types', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('districts', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('books', 'is_processed',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    # op.alter_column('books', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # op.alter_column('blocks', 'id',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
    #            existing_nullable=False,
    #            autoincrement=True)
    # ### end Alembic commands ###
    pass
