"""enhanced Models

Revision ID: c4c34bef9a13
Revises: 519440fcb72e
Create Date: 2025-02-13 02:00:35.351979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c34bef9a13'
down_revision: Union[str, None] = '519440fcb72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_block_district_name', 'blocks', ['district_id', 'name'], unique=False)
    op.create_index(op.f('ix_blocks_district_id'), 'blocks', ['district_id'], unique=False)
    op.create_index(op.f('ix_blocks_name'), 'blocks', ['name'], unique=False)
    op.create_index('ix_books_department', 'books', ['department'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.drop_constraint('districts_name_key', 'districts', type_='unique')
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)
    op.create_index('ix_gram_panchayat_block_name', 'gram_panchayats', ['block_id', 'name'], unique=False)
    op.create_index(op.f('ix_gram_panchayats_block_id'), 'gram_panchayats', ['block_id'], unique=False)
    op.create_index(op.f('ix_gram_panchayats_name'), 'gram_panchayats', ['name'], unique=False)
    op.create_index('ix_gr_department_effective_date', 'grs', ['department_name', 'effective_date'], unique=False)
    op.create_index(op.f('ix_grs_department_name'), 'grs', ['department_name'], unique=False)
    op.create_index(op.f('ix_grs_effective_date'), 'grs', ['effective_date'], unique=False)
    op.create_index('ix_user_documents_verification_status', 'user_documents', ['verification_status'], unique=False)
    op.create_unique_constraint('uq_user_document', 'user_documents', ['user_id', 'document_type_id'])
    op.create_unique_constraint('uq_userotp_user_id', 'user_otps', ['user_id'])
    op.create_unique_constraint(None, 'user_otps', ['user_id'])
    op.create_index(op.f('ix_users_block_id'), 'users', ['block_id'], unique=False)
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_gram_panchayat_id'), 'users', ['gram_panchayat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_gram_panchayat_id'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_index(op.f('ix_users_block_id'), table_name='users')
    op.drop_constraint(None, 'user_otps', type_='unique')
    op.drop_constraint('uq_userotp_user_id', 'user_otps', type_='unique')
    op.drop_constraint('uq_user_document', 'user_documents', type_='unique')
    op.drop_index('ix_user_documents_verification_status', table_name='user_documents')
    op.drop_index(op.f('ix_grs_effective_date'), table_name='grs')
    op.drop_index(op.f('ix_grs_department_name'), table_name='grs')
    op.drop_index('ix_gr_department_effective_date', table_name='grs')
    op.drop_index(op.f('ix_gram_panchayats_name'), table_name='gram_panchayats')
    op.drop_index(op.f('ix_gram_panchayats_block_id'), table_name='gram_panchayats')
    op.drop_index('ix_gram_panchayat_block_name', table_name='gram_panchayats')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.create_unique_constraint('districts_name_key', 'districts', ['name'])
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index('ix_books_department', table_name='books')
    op.drop_index(op.f('ix_blocks_name'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_district_id'), table_name='blocks')
    op.drop_index('ix_block_district_name', table_name='blocks')
    # ### end Alembic commands ###
